# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1873e2df1a15cf994b56e0b4fd9417c65bbaf0ebfb431daccf347eb781d257aa84659703a0483b887e97522b971fdc5ed642e2e61ea06bcd13afd2cf9bb462ef

test:
  secret_key_base: 19845efec2455b310c961cb8aa5df0715b02800b1428ad65b5522b42c160c72d50485fabd0794680d38de57671cbf566b17b35b964706227114b3e286357292f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
